import catalog from "./catalog.json";

// The catalog of spell check dictionaries, generated by
// scripts/build-dictionary-catalog.ts. The Rust side reads the same file.

interface Entry {
  package: string;
  version: string;
  license: string;
  bundled: boolean;
  // whether the dictionary can be loaded at all
  loads: boolean;
}

const aliases: Record<string, string> = catalog.aliases;
const dictionaries: Record<string, Entry> = catalog.dictionaries;

/**
 * dictionaryTag returns the tag of the dictionary for `tag`, e.g. "nb" for "no"
 */
export const dictionaryTag = (tag: string) => aliases[tag] ?? tag;

/**
 * hasDictionary returns whether spelling can be checked in `tag`
 */
export const hasDictionary = (tag: string) =>
  dictionaries[dictionaryTag(tag)]?.loads === true;

/**
 * isBundled returns whether the dictionary for `tag` is built into the app
 */
export const isBundled = (tag: string) =>
  dictionaries[dictionaryTag(tag)]?.bundled === true;

// the tags of all usable dictionaries, e.g. "de-CH" or "sr-Latn"
export const dictionaryTags: readonly string[] = Object.keys(dictionaries)
  .filter((tag) => dictionaries[tag].loads)
  .sort();
