language: go

branches:
  only:
    - master

go:
  - 1.5
  - 1.6

path:
  - "GOPATH=${TRAVIS_BUILD_DIR}/src:$GOPATH"

install:
  - go get github.com/constabulary/gb/...
  - go get github.com/golang/lint/golint
  - go get golang.org/x/tools/cmd/vet
  - go get -u github.com/jteeuwen/go-bindata/...
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover

  - npm install

before_script:
  - webpack
  - go-bindata -pkg="blank" -o src/blank/assets.go public/... tmpl/...

script:
  - golint src/
  - go tool vet src/
  - 'cd src && go test -covermode=count -coverprofile=../coverage.out blank && cd ..'
  - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN || true'

notifications:
  email:
    on_success: never
    on_failure: change

cache:
  directories:
    - node_modules