import { defineConfig } from "vite";
import { coverageConfigDefaults } from "vitest/config";

const host = process.env.TAURI_DEV_HOST;

// https://vitejs.dev/config/
export default defineConfig(async () => ({
  // Vite options tailored for Tauri development and only applied in `tauri dev` or `tauri build`
  //
  // 1. prevent vite from obscuring rust errors
  clearScreen: false,
  // 2. tauri expects a fixed port, fail if that port is not available
  server: {
    port: 1420,
    strictPort: true,
    host: host || false,
    hmr: host
      ? {
          protocol: "ws",
          host,
          port: 1421,
        }
      : undefined,
    watch: {
      // 3. tell vite to ignore watching `src-tauri`
      ignored: ["**/src-tauri/**"],
    },
  },

  test: {
    globals: true,
    include: ["src/**/*.test.ts"],
    setupFiles: ["./src/vitest.setup.ts"],
    environment: "jsdom",
    mockReset: true,
    restoreMocks: true,
    unstubGlobals: true,
    coverage: {
      include: ["**/src/**"],
      exclude: [
        ...coverageConfigDefaults.exclude,
        "**/src-tauri/**",
        // test infrastructure
        "src/test/**",
        "src/vitest.setup.ts",
        // generated by pdfmake, holds the embedded font
        "src/exporters/pdf/pdfmake-vfs.ts",
      ],
      thresholds: {
        statements: 80,
        branches: 80,
        functions: 80,
        lines: 80,
      },
    },
  },
}));
