import vue from "@vitejs/plugin-vue";
import { defineConfig } from "vite";
import { coverageConfigDefaults } from "vitest/config";

import { version } from "./package.json";

const host = process.env.TAURI_DEV_HOST;

// https://vitejs.dev/config/
export default defineConfig(async () => ({
  plugins: [vue()],

  // test-only hooks (see src/main.ts), in `bun run dev` and in the debug
  // builds the E2E tests run, for which the Tauri CLI sets TAURI_ENV_DEBUG
  define: {
    __TEST_HOOKS__: JSON.stringify(process.env.TAURI_ENV_DEBUG === "true"),
    // the version About shows where the app can't tell it, in `bun run dev`
    __APP_VERSION__: JSON.stringify(version),
  },

  // Vite options tailored for Tauri development and only applied in `tauri dev` or `tauri build`
  //
  // 1. prevent vite from obscuring rust errors
  clearScreen: false,
  // 2. tauri expects a fixed port, fail if that port is not available
  server: {
    port: 1420,
    strictPort: true,
    host: host || false,
    hmr: host
      ? {
          protocol: "ws",
          host,
          port: 1421,
        }
      : undefined,
    watch: {
      // 3. tell vite to ignore watching `src-tauri`
      ignored: ["**/src-tauri/**", "**/.claude/**"],
    },
  },

  test: {
    globals: true,
    include: ["src/**/*.test.ts"],
    setupFiles: ["./src/vitest.setup.ts"],
    environment: "jsdom",
    mockReset: true,
    restoreMocks: true,
    unstubGlobals: true,
    coverage: {
      include: ["**/src/**"],
      exclude: [
        ...coverageConfigDefaults.exclude,
        "**/src-tauri/**",
        // test infrastructure
        "src/test/**",
        "src/vitest.setup.ts",
        // decodes images with the webview and a canvas, which jsdom lacks
        "src/images/codec.ts",
        // loads Mermaid, which needs the webview to measure text, and what
        // older webviews lack for it
        "src/diagrams/mermaid.ts",
        "src/diagrams/polyfills.ts",
        // generated by scripts/build-engine.sh
        "src/engine/wasm/**",
        // test documents
        "**/__fixtures__/**",
        // nested git worktrees
        "**/.claude/**",
      ],
      thresholds: {
        statements: 80,
        branches: 80,
        functions: 80,
        lines: 80,
      },
    },
  },
}));
