//! The catalog of dictionaries Blank can check spelling with, generated by
//! scripts/build-dictionary-catalog.ts. The frontend reads the same file.

use std::{collections::BTreeMap, sync::LazyLock};

use serde::Deserialize;

#[derive(Debug, Deserialize)]
pub struct FileInfo {
    pub size: u64,
    pub sha256: String,
}

#[derive(Debug, Deserialize)]
pub struct Files {
    pub aff: FileInfo,
    pub dic: FileInfo,
}

#[derive(Debug, Deserialize)]
pub struct Entry {
    pub package: String,
    pub version: String,
    pub bundled: bool,
    // whether the dictionary can be loaded at all
    pub loads: bool,
    pub files: Files,
}

#[derive(Debug, Deserialize)]
pub struct Catalog {
    // language codes that use the dictionary of another tag, e.g. "no" → "nb"
    pub aliases: BTreeMap<String, String>,
    pub dictionaries: BTreeMap<String, Entry>,
}

pub static CATALOG: LazyLock<Catalog> = LazyLock::new(|| {
    serde_json::from_str(include_str!("../../../src/spellcheck/catalog.json"))
        .expect("the dictionary catalog is invalid")
});

/// resolve returns the tag of the dictionary for `tag` and its catalog entry
pub fn resolve(tag: &str) -> Option<(&'static str, &'static Entry)> {
    let tag = CATALOG.aliases.get(tag).map(String::as_str).unwrap_or(tag);
    CATALOG
        .dictionaries
        .get_key_value(tag)
        .map(|(tag, entry)| (tag.as_str(), entry))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn resolves_tags_and_aliases() {
        assert_eq!(resolve("de").map(|(tag, _)| tag), Some("de"));
        assert_eq!(resolve("de-CH").map(|(tag, _)| tag), Some("de-CH"));
        assert_eq!(resolve("no").map(|(tag, _)| tag), Some("nb"));
        assert!(resolve("fi").is_none());
        assert!(resolve("xx").is_none());
    }

    #[test]
    fn bundles_only_loadable_dictionaries() {
        let bundled: Vec<_> = CATALOG
            .dictionaries
            .iter()
            .filter(|(_, entry)| entry.bundled)
            .map(|(tag, entry)| {
                assert!(entry.loads, "{tag} is bundled but can't be loaded");
                tag.as_str()
            })
            .collect();
        assert_eq!(bundled, ["de", "en", "es", "fr"]);
    }
}
