// Embeds the TTF files from fonts/ into the pdfmake virtual file system used
// by the PDF export, and records which characters the main font covers so the
// export can fall back to DejaVu Sans for the rest. Run with
// `bun run fonts:vfs` after changing a font.
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { openSync, type Font } from "fontkit";

const MAIN_FONT = "IBMPlexSans-Regular.ttf";

const root = join(import.meta.dir, "..");
const fontsDir = join(root, "fonts");
const pdfDir = join(root, "src/exporters/pdf");

const files = readdirSync(fontsDir)
  .filter((file) => file.endsWith(".ttf"))
  .sort();

const vfs = Object.fromEntries(
  files.map((file) => [
    file,
    readFileSync(join(fontsDir, file)).toString("base64"),
  ]),
);

writeFileSync(
  join(pdfDir, "pdfmake-vfs.ts"),
  `// DO NOT EDIT!
// This file is generated by scripts/build-pdf-vfs.ts from the fonts in fonts/

export default ${JSON.stringify(vfs, null, 2)};
`,
);

// collapse the covered code points into [first, last] ranges
const font = openSync(join(fontsDir, MAIN_FONT)) as Font;
const ranges: [number, number][] = [];
for (const codePoint of [...font.characterSet].sort((a, b) => a - b)) {
  const last = ranges[ranges.length - 1];
  if (last && codePoint === last[1] + 1) last[1] = codePoint;
  else ranges.push([codePoint, codePoint]);
}

writeFileSync(
  join(pdfDir, "coverage.ts"),
  `// DO NOT EDIT!
// This file is generated by scripts/build-pdf-vfs.ts: the code point ranges
// covered by ${MAIN_FONT}

export default [
${ranges.map(([first, last]) => `  [${first}, ${last}],`).join("\n")}
] as [number, number][];
`,
);

console.log(
  `embedded ${files.join(", ")}; ${MAIN_FONT} covers ${font.characterSet.length} code points in ${ranges.length} ranges`,
);
