name: Tests

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v2

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - run: |
          bun install
          bun run lint
          bun run test:coverage
